name: Test Docker Image Build

on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

env:
  DEV: ${{ ((github.event.pull_request.base.ref != '' && format('refs/heads/{0}', github.event.pull_request.base.ref) || github.event.ref)) != 'refs/heads/main' && '-dev' || '' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      env:
        NODE_ENV: ${{ env.DEV == '' && 'production' || 'development' }}
      run:
        docker build . --file WebApp.Dockerfile --build-arg DEV=$DEV --build-arg NODE_ENV=$NODE_ENV --tag eschweighofer/sample-app-aoai-chatgpt:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER$DEV
